### PR TITLE
fix: correct message for functions in `use-baseline` rule

### LINKED ISSUE #293: Rule Change: Incorrect error message for CSS functions in `use-baseline` rule
### What rule do you want to change?

use-baseline

### What change do you want to make?

Other

### How do you think the change should be implemented?

Other

### Example code

```css
.a {
  color: light-dark(#333b3c, #efefec);
}
```

### What does the rule currently do for this code?

The rule reports:

```
Type 'light-dark' is not a widely available baseline feature.
```

This is confusing because `light-dark` is clearly a CSS function, not a "type". The term "type" is misleading and doesn't accurately describe what's being checked.

### What will the rule do after it's changed?

After the change, the rule will report:

```
Function 'light-dark' is not a widely available baseline feature.
```

### Participation

- [x] I am willing to submit a pull request to implement this change.

### Additional comments

The data generation script already correctly filters to only include CSS functions (by checking `mdnData.css.functions`), but currently exports them under the misleading name `types`. We should update the data export name to `functions` for consistency.

### PR DESCRIPTION
**Pull request by thecalamiity**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/.github/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request?

This pull request fixes an inaccurate error message in the `use-baseline` rule. Previously, CSS functions (such as `light-dark()` and `color-mix()`) were reported as “types,” which was misleading. The rule will now correctly refer to them as “functions.”

#### What changes did you make? (Give an overview)

- Renamed the exported baseline data key from `types` → `functions`.  
- Updated the `use-baseline` rule to:
  - Use `functions` instead of `types`.  
  - Replace the message ID `notBaselineType` with `notBaselineFunction`.  
  - Update the corresponding error message to use “Function” instead of “Type.”  
- Updated the baseline data generation script to export `functions` consistently.  
- Adjusted all affected test cases to match the new message ID and terminology.

#### Related Issues

Fixes #293

### CODE REVIEW

File: tools/generate-baseline.js [hunk 1]
```diff
@@ -210,7 +210,7 @@ export const BASELINE_FALSE = ${BASELINE_FALSE};
 export const properties = new Map(${JSON.stringify(Object.entries(cssFeatures.properties), null, "\t")});
 export const atRules = new Map(${JSON.stringify(Object.entries(cssFeatures.atRules), null, "\t")});
 export const mediaConditions = new Map(${JSON.stringify(Object.entries(cssFeatures.mediaConditions), null, "\t")});
-export const types = new Map(${JSON.stringify(Object.entries(cssFeatures.types), null, "\t")});
+export const functions = new Map(${JSON.stringify(Object.entries(cssFeatures.functions), null, "\t")});
```
Comment (nzakas) [inline tools/generate-baseline.js:213]: I don't think this is the correct approach here. Let's keep `types` as-is and just add `functions`.

Comment (thecalamiity) [reply tools/generate-baseline.js:213]: The "types" here are actually just functions. We're filtering the `css.types.*` entries through `mdnData.css.functions` to extract only the ones that represent actual CSS functions.

https://github.com/eslint/css/blob/c6c5b9ddbcde22b4c65381dce82c770de44e8b1e/tools/generate-baseline.js#L158-L160

Comment (nzakas) [reply tools/generate-baseline.js:213]: Ah gotcha, thanks for explaining. :+1:
