### PR TITLE
fix: recursively resolve custom properties in no-invalid-properties

### LINKED ISSUE #200: Bug: css variable not resolved in rule "css/no-invalid-properties"
### Environment

ESLint version: 9.31.0
@eslint/css version: 0.10.0
Node version: 24.4.0
npm version: 11.4.2
Operating System: macOS 15.5 (24F74)

### Which language are you using?

stylesheet

### What did you do?

<details>
<summary>Configuration</summary>

```
eslint css/no-invalid-properties: ["error"]
```
</details>

```css
/* eslint css/no-invalid-properties: ["error"] */

:root {
	--mySize: 80px;
	--myFontSize: calc(0.5 * var(--mySize));
}

.test {
	font-size: var(--myFontSize);
}
```

### What did you expect to happen?

No error as variable --myFontSize is properly defined.

### What actually happened?

Unknown property 'font-size' found  css/no-invalid-properties

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by xbinaryx**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/.github/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request?

This PR prevents the lexer from receiving unresolved `var()` expressions by recursively resolving chained CSS custom properties. Previously the rule only performed a single-level replacement (e.g. `--a: var(--b) → var(--b)`), so chained variables like `--a: var(--b); --b: 80px;` could still leave var() in the value passed to the lexer, causing `Error: Matching for a tree with var() is not supported.`

#### What changes did you make? (Give an overview)

- Implemented recursive/iterative resolution of custom properties so variables that reference other variables are resolved to their final, non-var() value before validation.
- Added tests

#### Related Issues

Fixes #200

### CODE REVIEW

File: src/rules/no-invalid-properties.js [hunk 1]
```diff
@@ -124,6 +140,99 @@ export default {
...
+		 * @param {Map<string, string>} cache Cache for memoization within a single resolution scope
+		 * @param {Set<string>} [seen] Set of already seen variables to detect cycles
+		 * @returns {string|null} The resolved value or null if not found
+		 */
+		function resolveVariable(variableName, cache, seen = new Set()) {
+			/** @type {Array<string>} */
+			const fallbackStack = [];
+			let currentVarName = variableName;
+
+			while (true) {
```
Comment (nzakas) [inline src/rules/no-invalid-properties.js:171]: Can you add some comments in this function to explain the algorithm?

File: src/rules/no-invalid-properties.js [hunk 2]
```diff
@@ -124,6 +140,99 @@ export default {
...
+		/**
+		 * Resolves a fallback text which can contain nested var() calls.
+		 * Returns the first resolvable value or null if none resolve.
+		 * @param {string} rawFallbackText
+		 * @param {Map<string, string>} cache Cache for memoization within a single resolution scope
+		 * @param {Set<string>} [seen] Set of already seen variables to detect cycles
+		 * @returns {string | null}
+		 */
+		function resolveFallback(rawFallbackText, cache, seen = new Set()) {
+			const trimmedFallback = rawFallbackText.trim();
```
Comment (nzakas) [inline src/rules/no-invalid-properties.js]: The fallback text is already trimmed in `parseVarFunction()`, so this isn't needed here.

File: src/rules/no-invalid-properties.js [hunk 3]
```diff
@@ -161,6 +270,8 @@ export default {
 
 				if (usingVars) {
 					const valueList = [];
+					/** @type {Map<string,string>} */
```
Comment (nzakas) [inline src/rules/no-invalid-properties.js]: Can we add a comment here explaining what `resolvedCache` is used for?

**Review by nzakas — CHANGES_REQUESTED** [review]
Nice work on this. Overall the code looks good, I think we just need some comments to help others understand how this works.
