### PR TITLE
fix: no-invalid-properties false positives for var() in functions

### LINKED ISSUE #223: Rule Change: no-invalid-properties incorrectly reports for valid CSS with var() in functions
### What rule do you want to change?

no-invalid-properties

### What change do you want to make?

Generate fewer warnings

### How do you think the change should be implemented?

A new default behavior

### Example code

```css
:root {
  --width: 10px;
}

div {
  width: calc(100% - var(--width))
}
```

### What does the rule currently do for this code?

The rule incorrectly reports: `Unknown property 'width' found`. This is a regression in the main branch, as the same code works correctly in v0.10.0.

### What will the rule do after it's changed?

The rule should recognize that `width` is a valid CSS property and that `calc(100% - var(--width))` is a valid value for the width property. It should not report any errors for this code.

### Participation

- [x] I am willing to submit a pull request to implement this change.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by thecalamiity**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/.github/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request?

This PR fixes a regression in the `no-invalid-properties` rule where it incorrectly reports for valid CSS properties containing `var()` usage within functions like `calc()`.

#### What changes did you make? (Give an overview)

- Updated the validation logic to properly handle CSS variables when they appear inside functions.
- Added tests to verify correct behavior for variables in functions

#### Related Issues

Fixes #223

### CODE REVIEW

File: src/rules/no-invalid-properties.js [hunk 1]
```diff
@@ -124,6 +124,127 @@ export default {
...
+						!processVarFunction(
+							nestedChild,
+							nestedValueList,
+							valuesWithVarLocs,
+						)
+					) {
+						return null;
+					}
+				} else if (nestedChild.type === "Function") {
+					// Recursively process nested functions
```
Comment (nzakas) [inline src/rules/no-invalid-properties.js]: Here we're doing a traversal on top of the traversal that is already happening in the rule, which is inefficient.

A more efficient approach would be to use the `Function` visitor method to do the traversal automatically. Can you take a look at that?

Comment (thecalamiity) [reply src/rules/no-invalid-properties.js]: I looked into using the Function visitor method here, but I don’t see a straightforward way to apply it. The code at this point isn’t just traversing—it’s reconstructing the property value as a string, including nested function names and arguments. The visitor pattern alone doesn’t provide the context needed for this reconstruction, so a manual traversal seems necessary. If you know of a way to leverage the visitor pattern for this case, I’d appreciate your input.

Comment (nzakas) [reply src/rules/no-invalid-properties.js]: You can start by looking at `Function > *` and `Function > *:exit`. You'd need to use a stack to keep track of the depth you're at, but otherwise, I think that should work.

**Comment by nzakas** [comment]
Can you check the test failures?

File: tests/rules/no-invalid-properties.test.js [hunk 2]
```diff
@@ -55,6 +55,37 @@ ruleTester.run("no-invalid-properties", rule, {
 		":root { --my-color: red; }\na { color: var(--my-color, var(--fallback-color, var(--foo, var(--bar)))) }",
 		":root { --my-color: red; }\na { color: var(--my-color, var(--fallback-color, var(--foo, var(--bar, blue)))) }",
 		":root { --color: red }\na { border-top: 1px var(--style, var(--fallback, solid)) var(--color, blue); }",
+		"a { width: calc(var(--my-width, 100px)) }",
```
Comment (snitin315) [inline tests/rules/no-invalid-properties.test.js:58]: Can we add the following test case as well when the variable is also using calc():

```css
/* eslint css/no-invalid-properties: "error" */

:root { --dynamic-width: calc(20px + 10px); }
  
div { width: calc(100% - var(--dynamic-width)); }
```

**Review by snitin315 — CHANGES_REQUESTED** [review]
We have one false positive, can you please check?

```css
/* eslint css/no-invalid-properties: "error" */

:root { 
    --dynamic-width: calc(20px + 10px); 
    --dynamic-width-2: calc(var(--dynamic-width) + 10px); 
}
  
.div { width: calc(100% - var(--dynamic-width)); } // ok
.div2 { width: calc(100% - var(--dynamic-width-2)); } // Error Unknown property 'width' found

```
