### PR TITLE
fix: handle missing declaration state in `no-invalid-properties`

### LINKED ISSUE #289: Bug: `css/no-invalid-properties` throws TypeError with certain valid CSS
### Environment

ESLint version: 9.37.0
@eslint/css version: 0.12.0
Node version: 22.18.0
npm version: N/A
Operating System: macOS

### Which language are you using?

stylesheet

### What did you do?

<details>
<summary>Configuration</summary>

```
// CSS rules
{
  files: ['**/*.css'],
  language: 'css/css',
  languageOptions: {
    tolerant: true,
  },
  plugins: { css },
  extends: [css.configs.recommended],
  rules: {
    'css/use-baseline': 'off',
    'css/no-invalid-properties': ['error', { allowUnknownVariables: true }],
  },
}
```
</details>

```css
@supports (color: color(display-p3 1 1 1)) {
  @media (color-gamut: p3) {
    & .my-class {
      --my-color: oklch(73.5% 0.1192 254.8);
    }
  }
}
```

```css
@import '@my/styles.css' layer(theme);
```

### What did you expect to happen?

Does not crash

### What actually happened?

TypeError: Cannot read properties of undefined (reading 'functionPartsStack')

Thrown from here: https://github.com/eslint/css/blob/268c7f03b981025e97c1489848212b5e9a27a9ab/src/rules/no-invalid-properties.js#L346

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/vitejs-vite-scw1hdur?file=src%2Fone.css

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by xbinaryx**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/.github/blob/master/CONTRIBUTING.md).

The rule assumed all `Function` nodes appear within a CSS declaration value. However, constructs such as `@import ... layer(theme`) or `@supports (color: color(display-p3 1 1 1))` can include `Function` nodes outside of any declaration context. Since `declStack` is only populated when entering a `Declaration` node, it was undefined for these cases — leading to:

```js
TypeError: Cannot read properties of undefined (reading 'functionPartsStack')
```

#### What is the purpose of this pull request?

This PR fixes a runtime error in the `no-invalid-properties` rule that occurred when the rule processed `Function` nodes outside of CSS declarations.

#### What changes did you make? (Give an overview)

- Added safe-guard checks in the `Function`, `Function > *:not(Function)`, and `Function:exit` visitors to ensure that a declaration state exists before accessing it.
- Added tests

#### Related Issues

Fixes #289

### CODE REVIEW

File: src/rules/no-invalid-properties.js [hunk 1]
```diff
@@ -356,6 +363,9 @@ export default {
 
 			"Function:exit"(node) {
 				const state = declStack.at(-1);
+				if (!state) {
```
Comment (Pixel998) [inline src/rules/no-invalid-properties.js]: You can combine these two checks into one condition:

```js
if (!state || state.skipValidation) {
  return;
}
```
